### ISSUE TITLE
Can 2.1.0 be tagged?

### ISSUE THREAD

**Issue by goetas** [hautelook/TemplatedUriRouter#23]
Symfony support seems working well (and https://github.com/hautelook/TemplatedUriBundle/pull/21 adds Symfony 4 support for the bundle)

**Comment by stof** [comment]
I'm also looking forward a release supporting Symfony 4.

**Comment by goetas** [comment]
https://github.com/hautelook/TemplatedUriRouter/releases/tag/2.0.3 has been tagged
